services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: discord_scraper
      POSTGRES_USER: discord_user
      POSTGRES_PASSWORD: discord_password
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U discord_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "127.0.0.1:6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
      args:
        ENABLE_BROWSER_AUTOMATION: ${ENABLE_BROWSER_AUTOMATION:-false}
    volumes:
      - ./backend:/app
      - ./exports:/app/exports
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DATABASE_URL: postgresql://discord_user:discord_password@postgres:5432/discord_scraper
      REDIS_URL: redis://redis:6379
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-default-dev-secret-key}
      FRONTEND_URL: http://localhost:3000
      TOKEN_ENCRYPTION_KEY: ${TOKEN_ENCRYPTION_KEY}
      ENABLE_SELFBOT_MODE: ${ENABLE_SELFBOT_MODE:-false}
      SELFBOT_WARNING_ACCEPTED: ${SELFBOT_WARNING_ACCEPTED:-false}
      SELFBOT_MIN_DELAY: ${SELFBOT_MIN_DELAY:-0.1}
      SELFBOT_MAX_DELAY: ${SELFBOT_MAX_DELAY:-0.2}
      SELFBOT_MESSAGES_PER_HOUR: ${SELFBOT_MESSAGES_PER_HOUR:-10000}
      EXPORT_SPLIT_ENABLED: ${EXPORT_SPLIT_ENABLED:-true}
      MAX_MESSAGES_PER_FILE: ${MAX_MESSAGES_PER_FILE:-500}
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
      args:
        ENABLE_BROWSER_AUTOMATION: ${ENABLE_BROWSER_AUTOMATION:-false}
    volumes:
      - ./backend:/app
      - ./exports:/app/exports
    environment:
      DATABASE_URL: postgresql://discord_user:discord_password@postgres:5432/discord_scraper
      REDIS_URL: redis://redis:6379
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      TOKEN_ENCRYPTION_KEY: ${TOKEN_ENCRYPTION_KEY}
      ENABLE_SELFBOT_MODE: ${ENABLE_SELFBOT_MODE:-false}
      SELFBOT_WARNING_ACCEPTED: ${SELFBOT_WARNING_ACCEPTED:-false}
      SELFBOT_MIN_DELAY: ${SELFBOT_MIN_DELAY:-0.1}
      SELFBOT_MAX_DELAY: ${SELFBOT_MAX_DELAY:-0.2}
      SELFBOT_MESSAGES_PER_HOUR: ${SELFBOT_MESSAGES_PER_HOUR:-10000}
      EXPORT_SPLIT_ENABLED: ${EXPORT_SPLIT_ENABLED:-true}
      MAX_MESSAGES_PER_FILE: ${MAX_MESSAGES_PER_FILE:-500}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: python worker.py

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      VITE_API_URL: http://localhost:8000
      VITE_WS_URL: ws://localhost:8000
    ports:
      - "127.0.0.1:3000:3000"
    command: npm run dev

volumes:
  postgres_data: